
    # Paths to read and save data
    parent_path: 
    path_csv: dataframes/CholecT45.csv
    train_path: data/
    output_dir:

    # Cholec80 phase annotations path
    phase : false
    cholec80_phase_path : # example: local_path/cholec80/phase_annotations
    
    # General Settings 
    debug: false
    device: cuda:0 
    

    # Hyperparameter
    exp: myexp
    nworkers: 12

    # Data split
    challenge_split: true
    n_fold : 5
    trn_fold: 
    - 0
    - 1
    - 2
    - 3
    - 4

    step_dom : 1
    step_min : 1
    
    # Target column param 
    col0: tri0
    target_size: 131
    target_col : multi_tri
    multi: true


    
    # Model hyperparams
    model_name: swin_base_patch4_window7_224   
    pretrained: true
    weight_dir : 
    local_weight : false
    pretrained_model: false


    
    
    # Augmentation params
    height: 224  
    width:  224  
    
    
    # Training params
    epochs: 20
    T_0: 21  # CosineAnnealingWarmRestarts
    lr: 2e-4
    min_lr: 2e-5
    batch_size: 64
    valid_batch_size: 64
    weight_decay: 1e-6
    seed: 142
    early_stopping : false



    # Self-distillation
    SD: 1
    distill : False

    # Label smoothing
    smooth : false
    ls : 0.1

    
    # Drop noisy frames
    drop_all: False
    drop_black: False
    filter_black: true

    # Leave out an independent test set of 5 videos
    test_inference: false

    # Inference
    save_folder :
    inference : true
    ensemble : False
    ensemble_models :

    # Neptune logging
    neplog: false
    neptune_project: 
    neptune_api_token:

    gradient_accumulation_steps: 2
    max_grad_norm: 1000
